### PR TITLE
XMLHelpers: fix signElement used by signMessage in cases where the XML doc is beautified

### PR DESCRIPTION
**Pull request by cnotin**
XML docs are beautified in the UI which adds line returns and spaces for indentation.
It caused errors here:
https://github.com/SAMLRaider/SAMLRaider/blob/0f9ccf6d89d1560e0cd6a11124a16629db8f9c0b/src/main/java/helpers/XMLHelpers.java#L657

```
java.lang.ClassCastException: com.sun.org.apache.xerces.internal.dom.DeferredTextImpl cannot be cast to org.w3c.dom.Element
        at helpers.XMLHelpers.signElement(XMLHelpers.java:657)
        at helpers.XMLHelpers.signMessage(XMLHelpers.java:577)
        at application.SamlTabController.resignMessage(SamlTabController.java:505)
        at gui.SamlPanelAction$9.actionPerformed(SamlPanelAction.java:199)
```

Because the `nextSibling` is a `TextNode` (containing "\n    ") which cannot be cast to `Element` thus triggering an exception and a failure to sign the message (UI label is stuck to "Signing....")

I added a testcase which triggers the issue and show that it's now fixed. I copied another test file, the only difference is here:
`</Issuer>\n      <samlp:Status>`

### CODE REVIEW

**Comment by mindfuckup** [comment]
Hi cnotin

Thanks for the PR, looks fine for me at the first glance!

I'll have a detailed look into it when I find some time to work on the project. Probably at some point before the end of the year. Then I can release a new version.

THX & GRZ,
Emanuel

**Comment by cnotin** [comment]
Awesome! Thanks for your answer :)

**Comment by cnotin** [comment]
Kind reminder ;)

**Comment by mindfuckup** [comment]
Thanks for the PR!

I will shortly fix nother bug and then release a new version.

**Pull request merged**
